networks: 
  main: 
    driver: bridge
    ipam: 
      config: 
        - subnet: 172.25.255.0/24
      driver: default
services: 
  nats-1: 
    command: 
      - "-D"
      - "-p"
      - "4222"
      - "-cluster"
      - "nats://0.0.0.0:5222"
    image: "nats:2.1.2"
    ports:
      - "14222:4222"
  nats-2: 
    command: 
      - "-D"
      - "-p"
      - "4222"
      - "-cluster"
      - "nats://0.0.0.0:5222"
      - "-routes"
      - "nats://nats-1:5222"
    image: "nats:2.1.2"
    ports:
      - "24222:4222"
  nats-3: 
    command: 
      - "-D"
      - "-p"
      - "4222"
      - "-cluster"
      - "nats://0.0.0.0:5222"
      - "-routes"
      - "nats://nats-1:5222"
    image: "nats:2.1.2"
    ports:
      - "34222:4222"
version: "3.7"
